# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
  obj = bld.create_ns3_program('access-node-example', ['access-node'])
  obj.source = 'access-node-example.cc'

  obj2 = bld.create_ns3_program('access-netdev-example', ['access-node', 'csma', 'internet', 'applications'])
  obj2.source = 'access-net-device-example.cc'

