# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('bfd-echo', ['core', 'internet'])
    module.source = [
        'model/bfd-echo.cc',
        'helper/bfd-echo-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('bfd-echo')
    module_test.source = [
        'test/bfd-echo-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'bfd-echo'
    headers.source = [
        'model/bfd-echo.h',
        'helper/bfd-echo-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()
