# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('access-node', ['core', 'network', 'ancp', 'csma', 'internet'])
    module.source = [
        'model/access-channel.cc',
        'model/access-net-device.cc',
        'model/access-port.cc',
        'model/access-profile.cc',
        'model/mcast-profile.cc',
        'helper/access-node-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('access-node')
    module_test.source = [
        'test/access-node-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'access-node'
    headers.source = [
        'model/access-channel.h',
        'model/access-net-device.h',
        'model/access-port.h',
        'model/access-profile.h',
        'model/mcast-profile.h',
        'helper/access-node-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()
